### ISSUE TITLE
ImportError: No module named rnacommender.data

### ISSUE THREAD

**Issue by ozery** [gianlucacorrado/RNAcommender#5]
Hello,
I have installed the tool pre-requirements, however, I get the following import error:

`$ cd RNAcommender-master/rnacommender/`
`$ python recommend.py -h`
`Traceback (most recent call last):`
`  File "recommend.py", line 14, in <module>`
`    from rnacommender.data import PredictDataset`
`ImportError: No module named rnacommender.data`

Could you please let me know what the problem could be?
Thanks,
Ivan

**Comment by gianlucacorrado** [comment]
The scripts are already executable. Try:
`./recommend.py -h`
this should fix the problem.

Thank you for the message. I'll update the readme file in the documentation.
Cheers
Gianluca

**Comment by ozery** [comment]
Hello Gianluca,

Thank you for the answer. However, I still get the same error:

```
$ ./recommend.py -h
Traceback (most recent call last):
  File "./recommend.py", line 14, in <module>
    from rnacommender.data import PredictDataset
ImportError: No module named rnacommender.data
```

Ivan

**Comment by gianlucacorrado** [comment]
OK. In my case I was getting the same error before calling
`./recommend.py -h`.
I guess the problem is in your $PYTHONPATH. Please pull the new version of the repo. I've added a file named setup.py. This file is located in the RNAcommender folder. Try to execute
`python setup.py install`. 
This script should create a folder named rnacommender.egg-info. Now from the current path where the folder has been created try:
`./rnacommender/recommend.py -h`

I hope this helps otherwise just drop me another message.
Thank you very much

**Comment by ozery** [comment]
Yes, it worked this time (after the additionally installation of the "pandas" package).

Thanks!

**Comment by gianlucacorrado** [comment]
OK great to hear that!

Thank you again
